package com.agentcrawler.core;

public enum ErrorCode {
    INVALID_REQUEST,
    CONVERSATION_NOT_FOUND,
    AGENT_TIMEOUT,
    AGENT_ERROR,
    GENERATION_STOPPED,
    SITE_RETRY_LIMIT,
    CRAWL_FAILED,
    RATE_LIMITED,
    VISION_FAILED,
    UPLOAD_FAILED
}
